# Generated by Django 4.0.6 on 2022-07-14 06:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tweet_category',
            new_name='TweetCategory',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 6, 33, 26, 770286, tzinfo=utc)),
        ),
    ]
