# Generated by Django 4.0.6 on 2022-07-14 07:32

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_rename_tweet_category_tweetcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 7, 32, 10, 293920, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet',
            field=models.TextField(validators=[django.core.validators.RegexValidator('^[A-Za-z]$', 'Tweet must start with Character')]),
        ),
    ]
