# Generated by Django 4.0.6 on 2022-07-14 07:34

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_alter_tweet_created_at_alter_tweet_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 7, 34, 37, 597350, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet',
            field=models.TextField(validators=[django.core.validators.RegexValidator('^[A-Za-z]*$', 'Tweet must start with Character')]),
        ),
    ]
