# Generated by Django 4.0.6 on 2022-07-14 08:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_alter_tweet_created_at_alter_tweet_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='approval',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 8, 57, 9, 746584, tzinfo=utc)),
        ),
    ]
