# Generated by Django 4.0.6 on 2022-07-14 11:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0009_alter_tweet_created_at_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_reply', to='tweet.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='visibility',
            field=models.CharField(choices=[('show', 'SHOW'), ('hidden', 'hidden')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweet_comments', to='tweet.tweet'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 11, 14, 54, 474220, tzinfo=utc)),
        ),
    ]
