# Generated by Django 4.0.6 on 2022-07-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0010_comment_reply_comment_visibility_alter_comment_tweet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
