# Generated by Django 4.0.6 on 2022-07-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0011_alter_tweet_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='visibility',
            field=models.CharField(choices=[('show', 'SHOW'), ('hidden', 'HIDDEN')], default='pending', max_length=20),
        ),
    ]
