# Generated by Django 4.0.6 on 2022-07-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0013_alter_comment_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='expiry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
