# Generated by Django 4.0.6 on 2022-07-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0015_alter_comment_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.BooleanField(default=False),
        ),
    ]
